# Generated by Django 4.1.5 on 2023-06-28 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wed', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='site_id',
        ),
    ]
