# Generated by Django 3.2.12 on 2023-07-05 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wed', '0002_remove_feedback_site_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='staff',
            field=models.CharField(max_length=30, null=True, verbose_name='staff'),
        ),
    ]
